semlanik/qtprotobuf

examples/addressbook/addressbookengine.cpp
examples/simplechat/simplechatengine.cpp
src/generator/clientgenerator.cpp
src/generator/templates.cpp
src/grpc/CMakeLists.txt
src/grpc/qabstractgrpcclient.cpp
src/grpc/qabstractgrpcclient.h
src/grpc/qgrpcasyncoperationbase.cpp
src/grpc/qgrpcasyncoperationbase_p.h
src/grpc/qgrpcasyncreply.cpp
src/grpc/qgrpcasyncreply.h
src/grpc/qgrpcsubscription.h
tests/test_grpc/clienttest.cpp

- Remove update signals from generated clients. It's required because
of multiple subscriptions possible for single streaming method.
If user whould like to subscribe multiple times, it's not possible
to determine which subscription invoked signal.
- Add subscription reusage mechanism
- Implement tests for ducplicates
- Make QGrpcSubscription to serve multiple handlers

Implement subscriptions reusage

---

README.md
examples/qmakeexample/main.cpp
examples/qmakeexample/qmakeexample.pro
examples/qmakeexample/test1.proto
examples/qmakeexample/test2.proto
src/grpc/CMakeLists.txt
src/grpc/qgrpccredentials.h
src/grpc/qt_lib_grpc.pri.in
src/protobuf/CMakeLists.txt
src/protobuf/qt_lib_protobuf.pri.in

- Add .pri files for protobuf and grpc
- Add qtprotobuf_generate for qmake build procedures
- Add sample qmake-based application to show usage
- Update README
TODO: well-known types will be integrated under separate task
Fixes: #52

Add basic qmake build procedures support

---

src/generator/classgeneratorbase.cpp
src/generator/classgeneratorbase.h
src/generator/protobufclassgenerator.cpp
src/generator/templates.cpp
src/generator/templates.h
tests/test_protobuf/jsonserializationtest.cpp
tests/test_protobuf/simpletest.cpp.inc
tests/test_protobuf_multifile/CMakeLists.txt
tests/test_qml/qml/tst_simple.qml
tests/test_wellknowntypes/simpletest.cpp

- Add extra qml alias property generation for int32/uint32
based transparent fields
- Prohibit usage of 64-bit integers from QML code by default
- Implement and update tests

Implement qml aliasing for transparent fields

---

README.md
src/generator/classgeneratorbase.cpp
src/generator/protobufsourcegenerator.cpp
src/generator/templates.cpp
tests/test_protobuf/simpletest.cpp.inc
tests/test_qml/qml/tst_simple.qml
tests/test_wellknowntypes/simpletest.cpp

- From this point QtProtobuf will use standard protobuf name
converter for field names to camel case

Migrate to cAmEl case field names

---

CMakeLists.txt
src/generator/protobufsourcegenerator.cpp
src/generator/templates.cpp
src/generator/templates.h

- Add empty message copy and move functions with no argument
passed as parameter
Fixes: #94

Fix empty message warning

---

src/protobuf/qprotobufjsonserializer.cpp
tests/test_protobuf/jsondeserializationtest.cpp

- Add null value handling for all basic types
- Add Infinity, -Inifinity and NaN values handling for float/double
types
- Add default value assignment for enum types
- Update tests
Fixes: #106

Implement "invalid" fields handling in json serializer

---

cmake/QtProtobufGen.cmake
examples/addressbookserver/CMakeLists.txt
examples/simplechatserver/CMakeLists.txt
src/wellknowntypes/CMakeLists.txt
tests/test_qml/CMakeLists.txt
tests/test_qprotobuf_serializer_plugin/CMakeLists.txt

- Migrate to OBJECT library for generated code
- Cleanup cmake procedures
Fixes: #113

Fix static build for well-known types

---

.travis.yml
examples/simplechat/simplechatengine.cpp
src/generator/descriptorprinterbase.h
src/generator/generatorbase.cpp
src/generator/generatorbase.h
src/generator/generatorcommon.cpp
src/generator/generatorcommon.h
src/generator/messagedeclarationprinter.cpp
src/generator/messagedeclarationprinter.h
src/generator/messagedefinitionprinter.cpp
src/generator/messagedefinitionprinter.h
src/generator/multifilegenerator.cpp
src/generator/singlefilegenerator.cpp
src/generator/templates.cpp
src/generator/templates.h
src/protobuf/qprotobufjsonserializer.cpp
tests/test_grpc/clienttest.cpp
tests/test_protobuf/CMakeLists.txt
tests/test_protobuf/nestedtest.cpp
tests/test_protobuf/nestedtest.cpp.inc
tests/test_protobuf/proto/nestedmessages.proto
tests/test_protobuf/simpletest.cpp.inc
tests/test_protobuf_multifile/CMakeLists.txt
tests/test_protobuf_multifile/nestedtest.cpp

- Add support of multi-level nested types generation. Level limited
by generator stack size.
- Refactor protobuf class printers to support nested types
- Fix issue with local enums generation, introduced in previous
refactoring phase
- Add basic nested types tests
- Fix few minor coding-style issues
Fixes: #122

Implement basic nested types support

---

CMakeLists.txt
conanfile.py
src/protobuf/CMakeLists.txt

Added basic Conan support.
Conan installs compiler and libraries correctly, but I couldn't make it install QML modules to a correct location, because that location (QT_INSTALL_QML) is actually located inside another package. So I doubt, that this issue could be resolved without some changes to Qt package or to Conan itself.
Also, it depends on grpc from this repo: https://github.com/inexorgame/conan-grpc, at least, until grpc hits bincrafters or conan-center.

Add Conan support

---

src/grpc/quick/qquickgrpcsubscription.cpp
src/grpc/quick/qquickgrpcsubscription_p.h

The property allows to propagate the value changed event to any object which is bound to a property of the return value: this way there is no need to update manually the values through the updated callback.
That way, given the following example proto file:
```proto
service Analyzer {
rpc Subscribe (google.protobuf.Empty) returns (stream State);
}
message State {
bool on = 1;
}
```
Once subscribed with GrpcSubscription i can listen for updates from the stream directly with the returnValue property:
```qml
GrpcSubscription {
id: sub
client: AnalyzerClient
method: "Subscribe"
argument: Empty {}
enabled: true
}
Text {
text: sub.returnValue.on
}
```

Add "returnValue" property to qml GrpcSubscription

---

src/protobuf/qabstractprotobufserializer.h
src/protobuf/qprotobufjsonserializer.cpp
tests/test_protobuf/deserializationtest.cpp
tests/test_protobuf/jsondeserializationtest.cpp

- Make all fields default before serialization. It's required to
update values for fields that was not present in serialized blob
Fixes: #142

Reset all fields to default values before serialization

---

src/grpc/qgrpcchannel.cpp
src/grpc/qgrpcchannel_p.h

Hi @semlanik!
This fixes a build issue with include files that occurred on the most recent versions of gRPC (1.33.0 at least).
This was also a generic issue, because i think `_impl.h` files are not supposed to be included directly.

Grpc native channel: fixes for newer gRPC versions

---

src/generator/clientdeclarationprinter.cpp
src/generator/clientdefinitionprinter.cpp
src/generator/templates.cpp
src/generator/templates.h
tests/test_grpc_qml/qml/tst_grpc.qml

Hi @semlanik,
This pull request implements a new fature in the generator that adds a new QML RPC method that in place of the second callback accepts a pointer to the return object. An example is reported below:
```qml
Message {
id: arg
}
Message {
id: ret
}
function call() {
client.method(arg, ret, function(err) {
console.log("Error");
}
}
```
I've implemented a simple test, too.

Add a QML RPC method with the return value as a parameter

---

examples/fieldenum/README.md
examples/fieldenum/field_enum_example.cpp
examples/fieldenum/field_enum_example.pro
examples/fieldenum/field_enum_example.proto
src/generator/generatorbase.h

Truth be told, the .pro file is incomplete, but if you manually invoke protoc something like this:
QT_PROTOBUF_OPTIONS="FIELDENUM" protoc --plugin=protoc-gen-qtprotobuf=/usr/local/bin/qtprotobufgen --qtprotobuf_out=. field_enum_example.proto
then it will compile.

working example of field enums

---

src/protobuf/CMakeLists.txt
src/protobuf/QtProtobufConfig.cmake.in

- Move microjson for newer version
- Link microjson as object library independent of build type

Make microjson build-in only

---

src/generator/messagedefinitionprinter.cpp
src/generator/templates.cpp
src/protobuf/qprotobufjsonserializer.cpp
src/protobuf/qprotobufmetaproperty.cpp
src/protobuf/qprotobufmetaproperty.h
src/protobuf/qprotobufserializer.cpp
src/protobuf/qtprotobuftypes.h
tests/testscommon.h

- Current approach of mapping property names is not fully
compatible with JSON serializing. This causes many design
issues especially with the field aliases. So the explicit JSON
reflection is the only suitable solution for this.
- Update tests.

Add reflection of the json name to the property ordering

---

src/generator/parsemessages.go
src/generator/templates.cpp
tests/test_protobuf/deserializationtest.cpp
tests/test_protobuf/jsondeserializationtest.cpp
tests/test_protobuf/jsonserializationtest.cpp
tests/test_protobuf/proto/nopackage.proto
tests/test_protobuf/proto/nopackageexternal.proto
tests/test_protobuf/proto/simpletest.proto
tests/test_protobuf/serializationtest.cpp
tests/test_protobuf/simpletest.cpp
tests/test_protobuf/simpletest.cpp.inc
tests/test_protobuf_multifile/simpletest.cpp
tests/test_qml/qml/tst_simple.qml

- protobuf does not require the package to be specified in the
.proto file. Remove the associated checks from the
parsemessages.go script to continue generating messages
without the specified package.
- Add and update tests
Fixes: #192

Make the protobuf package optional

---

CMakeLists.txt
cmake/QtProtobufGen.cmake
cmake/QtProtobufInternalHelpers.cmake
src/qttypes/CMakeLists.txt
src/wellknowntypes/CMakeLists.txt

- Add support of the custom install paths for the add_*
functions.
- Move installation rules to the end of the project, to make sure
that the generated headers are included to the PUBLIC_HEADER
set of the target.
- Add the generated headers to the target if it's specified in
qtprotobuf_generate function call.
Fixes: #197

Fix installation rules

---

src/generator/templates.cpp
src/qttypes/CMakeLists.txt
src/wellknowntypes/CMakeLists.txt

- Q_ASSERT is expanded to nothing in relase builds so the QML
type registration is never happen for the release builds.
Remove redundant Q_ASSERT wrappers.
- Fix the header installtion path of the 'WellKnownTypes' and
'QtTypes' libraries.
Fixes: #201 #197

Fix couple regressions

---

CMakeLists.txt
cmake/FindWrapProtobuf.cmake
src/generator/QtqtprotobufgenConfig.cmake.in
src/wellknowntypes/QtProtobufWellKnownTypesConfig.cmake.in

- WrapProtobuf should only find required for the project needs
components. E.g. at the build time it's optional to have protoc
or libprotobuf in place. We may skip build of their dependencies
instead.
Fixes: #205

Split WrapProtobuf module into components

---

src/generator/messagedefinitionprinter.cpp
src/generator/templates.cpp
src/generator/templates.h
src/protobuf/qtprotobuftypes.h
tests/test_protobuf/simpletest.cpp.inc
tests/test_protobuf_multifile/simpletest.cpp

- Fix the way how repeated types are compared. Since protobuf doesn't
strict the order of repeated types we should avoid dummy comparing
of QList, but look for the items. This causes higher lookup
complexity but better work.
- QList containing QSharedPointer returns tru only if the pointer
values of QSharedPointer are the same but not actual values in the
structures. This is critical issue since lists containing the same
values return faulty false values
Fixes #229

Fix comparing of repeated types

---

src/generator/templates.cpp
tests/test_protobuf/simpletest.cpp.inc

- Getter had const modifier because of one of initial implementation
when the reference to the class member was returned. Now when getter
dereferences shared pointer it's easy to do.
- Add tests
Fixes #253

Remove const modifier from the return value of a message field getter

---

src/generator/messagedeclarationprinter.cpp
src/generator/templates.cpp
src/generator/templates.h
tests/test_extra_namespace_qml/test.h
tests/test_grpc_qml/test.h
tests/test_protobuf/simpletest.cpp.inc
tests/test_qml/qml/tst_simple.qml
tests/test_qml/test.h
tests/test_wellknowntypes/simpletest.cpp

- Remove 'Data' suffix from the enum list name.
- Add Qml tests for the enum lists.
- Expose the extended Qt version in Qml tests
Note: The elementrs of the enum list are represented as 'object's
in QML. That makes impossible to compare them with the enum value.
This was fixed in Qt 6 already, and perhaps in commercial releases
of Qt5.
Fixes #255

Fix the name of the enum list

---

src/grpc/qabstractgrpcclient.cpp
src/grpc/qgrpchttp2channel.cpp

- Handle the gRPC errors if the assigned QNetworkReply is finished
without network error and send the QGrpcStream::finish() signal
if no gRPC error received from server.
- Cancel all gRPC streams when re-attaching the channel.
Fixes #259

Fix handling of gRPC errors when the stream is finished

---

cmake/deb.cmake

that is, redundant to the `protobuf-compiler` dependency:
```bash
root@c83c70b8da59:/# apt info protobuf-compiler
Package: protobuf-compiler
Version: 3.12.4-1ubuntu7
<snip>
Depends: libc6 (>= 2.34), libgcc-s1 (>= 3.3.1), libprotoc23 (= 3.12.4-1ubuntu7), libstdc++6 (>= 5.2)
<snip>
root@c83c70b8da59:/# apt info libprotoc23      
Package: libprotoc23
Version: 3.12.4-1ubuntu7
<snip>
Depends: libc6 (>= 2.34), libgcc-s1 (>= 3.3.1), libprotobuf23 (>= 3.12.4), libstdc++6 (>= 11)
```

the libprotoc17 dependency is redundant and causes issues with ubuntu 22.04
