cmake/QtProtobufCommon.cmake
@gmabey could you please check this fix for #2  Thank you!
=> Add pthread detection for binaries that uses 3rdparty libs directly

src/generator/templates.cpp
=> Make return value of simple types getters constant

src/protobuf/qabstractprotobufserializer.cpp
=> Add handlers container protection for multithreading

src/generator/protobufsourcegenerator.cpp, src/generator/templates.cpp, src/generator/templates.h, tests/test_protobuf/simpletest.cpp.inc
- Add update signals for repeated fields when move semantics is used
Fixes: #48
=> Fix repeated field update signals

README.md, cmake/QtProtobufCommon.cmake, cmake/QtProtobufGen.cmake, examples/addressbook/CMakeLists.txt, examples/simplechat/CMakeLists.txt, src/protobuf/qabstractprotobufserializer.h, src/wellknowntypes/CMakeLists.txt
=> Rename generate_qtprotobuf to qtprotobuf_generate

README.md, cmake/QtProtobufCommon.cmake, cmake/QtProtobufGen.cmake, src/generator/classgeneratorbase.h, src/generator/generatoroptions.cpp, src/generator/generatoroptions.h, src/generator/protobufclassgenerator.cpp, src/generator/singlefilegenerator.cpp, src/generator/utils.h, tests/test_protobuf/proto/annotation.proto
- Copy comments for messages and fields in .proto file to generated
headers accordingly
Fixes: #65
=> Add code annotations generation

.ci/Dockerfile.opensuse_static, .ci/Dockerfile.ubuntu_static, .github/workflows/branchpush.yml
- Add targets for static builds ci checks
- Add extra target branch for ci tests
Fixes: #71
=> Add static build ci checks

.ci/qt_installer_windows.qs, .travis.yml, README.md, tests/test_qml/CMakeLists.txt
- Add travis-ci integration
- Fix issues in test_qml related to wellknowntypes
- Add badge to README
=> Add travis-ci integration for Windows build verification

cmake/QtProtobufTest.cmake, tests/test_grpc/test_driver.bat.in
- Server app should wait till Cliente finishes
=> Add windows test fix

CMakeLists.txt, README.md, cmake/rpm.cmake
- Add RPM generation using CPack
- Update README
Fixes: #47
=> Add rpm package distribution

.github/workflows/tagadd.yml, CMakeLists.txt
=> Add microjson submodule to release build

README.md, doxygen/Doxyfile.in, examples/CMakeLists.txt, examples/clienttutorial/CMakeLists.txt, examples/clienttutorial/echoclientengine.cpp, examples/clienttutorial/echoclientengine.h, examples/clienttutorial/main.cpp, examples/clienttutorial/main.qml, examples/clienttutorial/qml.qrc, examples/clienttutorial/tutorial.proto, examples/clienttutorial/tutorialserver/build_and_run.sh, examples/clienttutorial/tutorialserver/main.go, src/generator/main.cpp, src/protobuf/qtprotobuftypes.h
- Add complete client tutorial with doxygen description
- Update README
- Fix few documentation issue
- Migrate to major.minor version for documentation indentification
=> Add client tutorial sample

src/qttypes/QtProtobuf/QtCore.proto, src/qttypes/QtProtobuf/QtGui.proto, src/qttypes/qtprotobufqttypes.cpp, tests/test_qttypes/qtcoretest.cpp, tests/test_qttypes/qtguitest.cpp
@gmabey here are changes that we discussed about. I will align tests and submit them tomorrow. Please let me know if any changes are left.
=> Rework some of Qt types messages

src/grpc/quick/qquickgrpcsubscription.cpp, tests/test_grpc_qml/qml/tst_grpc.qml
=> Add subscription cancellation for QQuickGrpcSubscription

src/generator/messagedeclarationprinter.cpp, src/generator/messagedefinitionprinter.cpp, src/generator/singlefilegenerator.cpp, tests/test_wellknowntypes/simpletest.cpp
- Add covertsion from google.protobuf.Timestamp to QDateTime and back
- Update tests
Fixes: #85
=> Add covertion of google.protobuf.Timestamp

src/grpc/qabstractgrpcclient.cpp, src/grpc/qgrpchttp2channel.cpp
- Fix lambda memory leak for subscription, when error occured
Fixes: #157
=> Add disconnect for subscription

src/grpc/qabstractgrpcclient.cpp, tests/test_grpc/clienttest.cpp
- Add 1 second timeout for subscription fail
- Add tests
Fixes: #159
=> Add timeout for subscription error

README.md, src/grpc/CMakeLists.txt, src/grpc/qgrpcchannel.cpp, src/grpc/qgrpcchannel.h, src/grpc/qgrpcchannel_p.h, tests/test_grpc/CMakeLists.txt, tests/test_grpc/clienttest.cpp, tests/test_grpc/echoserver/main.cpp, tests/test_grpc/secureechoserver/main.cpp, tests/test_grpc/sslclienttest.cpp, tests/test_grpc_qml/CMakeLists.txt, tests/test_grpc_qml/grpc_http.cpp, tests/test_grpc_qml/grpc_socket.cpp, tests/test_grpc_qml/http2.cpp
This is a basic pull request referring to issue #145.
It is still not ready to merge, however if you could give me some feedback on the implementation that would be great!
=> Add basic implementation of a QAbstractGrpcChannel based on gRPC C++

.ci/Dockerfile.opensuse, .ci/Dockerfile.opensuse_static, .ci/Dockerfile.ubuntu, .ci/Dockerfile.ubuntu_static
- Migate to the last OSS release of Qt 5
=> Migate to Qt 5.15.2 in CI

cmake/QtProtobufGen.cmake, src/grpc/qtgrpcglobal.h, src/protobuf/qprotobuflazymessagepointer.h, src/protobuf/qtprotobufglobal.h, src/qttypes/CMakeLists.txt, src/wellknowntypes/CMakeLists.txt
- Add conditional compilation of the QML-related code
- Throw fatal error if generating of the QML code is enabled
but QML is not found
Fixes #239
=> Add QML realted conditions
